name: CMake

on:
  push:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: ARM runner
      uses: pguyot/arm-runner-action@v2.2.0
      with:
        base_image: raspios_lite_arm64:latest
        cpu: cortex-a53
        commands: |
          apt-get install --no-install-recommends -y make gcc libc6-dev cmake
          cmake --log-level=VERBOSE -B ${{env.github.workspace}}/native -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          cmake --log-level=VERBOSE -B ${{env.github.workspace}}/intrin -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_WITH_ARM_INTRINSICS=ON
          cmake --build ${{env.github.workspace}}/native --config ${{env.BUILD_TYPE}}
          cmake --build ${{env.github.workspace}}/intrin --config ${{env.BUILD_TYPE}}
          cd ${{env.github.workspace}}/native && ctest -C ${{env.BUILD_TYPE}}
          cd ${{env.github.workspace}}/intrin && ctest -C ${{env.BUILD_TYPE}}